vendor: Inspur Cloud
name: Inspur Cloud Container Engine and Inpsur Open Platform
version: v1.14.3
website_url: https://cloud.inspur.com/product/UK8S/
documentation_url: https://console1.cloud.inspur.com/document/cks/index.html
product_logo_url: https://upload.wikimedia.org/wikipedia/commons/a/a8/Inspur.svg