vendor: Inspur Cloud
name: Inspur Open Platform for ARM
version: v1.14.3
website_url: http://www.inspur.com/lcjtww/2315499/2315503/2317662/2318105/2332890/index.html
documentation_url: http://www.inspur.com/eportal/fileDir/defaultCurSite/resource/cms/2017/02/2017022309472517392.pdf
product_logo_url: https://upload.wikimedia.org/wikipedia/commons/a/a8/Inspur.svg